// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd4WnI1z1OpCl6N_axfArlX8rhNllDUqo',
    appId: '1:46976491622:web:1548641259af3191a40da7',
    messagingSenderId: '46976491622',
    projectId: 'focus-bits',
    authDomain: 'focus-bits.firebaseapp.com',
    storageBucket: 'focus-bits.appspot.com',
    measurementId: 'G-JEZE54G7GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCih1Ti1YKgKSIjlr2uwtIGbZvrmjyMtC0',
    appId: '1:46976491622:android:1e0cbc3a7845396da40da7',
    messagingSenderId: '46976491622',
    projectId: 'focus-bits',
    storageBucket: 'focus-bits.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq8dk7WW1s5nnX3hu-9FD5J-nrkOKIMlk',
    appId: '1:46976491622:ios:b12b5b8eba200b4aa40da7',
    messagingSenderId: '46976491622',
    projectId: 'focus-bits',
    storageBucket: 'focus-bits.appspot.com',
    iosClientId: '46976491622-kun9a0ciui5vjhub4hok7r2d07o318o5.apps.googleusercontent.com',
    iosBundleId: 'ar.v.focusbits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq8dk7WW1s5nnX3hu-9FD5J-nrkOKIMlk',
    appId: '1:46976491622:ios:d5ecb38d6adeedfea40da7',
    messagingSenderId: '46976491622',
    projectId: 'focus-bits',
    storageBucket: 'focus-bits.appspot.com',
    iosClientId: '46976491622-f1938gv3mdn5up2ih664g39agbighpbm.apps.googleusercontent.com',
    iosBundleId: 'ar.focusbits',
  );
}
